spring:
  application:
    name: module13.config

  cloud:
    config:
      server:
        git:
          uri: https://github.com/mdirfancse2023/module12.config
          default-label: main

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8888



